#:schema node_modules/wrangler/config-schema.json
name = "peconavi"
main = "worker/src/index.ts"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "peconavi-cache"
database_id = "9a1e61b6-d6bf-42d3-b310-62e495183698"
migrations_dir = "drizzle"
